GET http://localhost:5118/api/v1/employees

###

GET http://localhost:5118/api/v1/employees/

###

POST http://localhost:5118/api/v1/employees
content-type: application/json

{
    "name": "Foo",
    "surname": 5,
    "gender": "male",
    "email": "foo@gipo.dev",
    "town": "Padova"
}

###

DELETE http://localhost:5090/api/v1/employees

###

PATCH http://localhost:5090/api/v1/employees/
Content-Type: application/json

{
    "name": "changed",
    "surname": 5,
    "gender": "male",
    "email": "foo@gipo.dev",
    "town": "Padova"
}
