GET http://localhost:5118/api/v1/employees

###

GET http://localhost:5118/api/v1/employees/ae78434d-1588-410c-8596-86decf60ee21

###

POST http://localhost:5118/api/v1/employees
content-type: application/json

{
  "name": "Foo",
  "surname": "Bar",
  "gender": "male",
  "email": "foo@gipo.dev",
  "birthdate": "2015-12-30T23:00:00+00",
  "town": "Padova"
}

###

DELETE http://localhost:5118/api/v1/employees/ae78434d-1588-410c-8596-86decf60ee21

###

PATCH http://localhost:5118/api/v1/employees/ae78434d-1588-410c-8596-86decf60ee21
Content-Type: application/json

{
    "name": "changed",
    "surname": "changed",
    "gender": "male",
    "email": "foo@gipo.dev",
    "birthdate": "2015-12-30T23:00:00+00",
    "town": "Padova"
}
